project:
  type: book
  output-dir: _book

book:
  title: "Remember Book Example"
  author: "Mickaël Canouil"
  chapters:
    - index.qmd
    - chapter-two.qmd
    - chapter-three.qmd

format:
  html:
    theme: cosmo

filters:
  - ../../_extensions/remember/remember.lua

extensions:
  remember:
    separate-chapter-state: true
    page-exclude:
      - /drafts/*
